# Generated by Django 5.0.4 on 2024-05-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='certificate_ID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='nid',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='verification',
            field=models.BooleanField(default=False),
        ),
    ]
