# Generated by Django 5.0.1 on 2024-06-19 15:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quotation_by', models.CharField(blank=True, max_length=200, null=True)),
                ('items', models.JSONField(blank=True, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('createdAt', models.CharField(blank=True, max_length=200, null=True)),
                ('updatedAt', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
