# Generated by Django 5.0.1 on 2024-06-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='items',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
