# Generated by Django 5.0.1 on 2024-06-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('EUR', 'EUR'), ('NGN', 'NGN'), ('GBP', 'GBP'), ('PHP', 'PHP'), ('KES', 'KES'), ('TZS', 'TZS'), ('UGX', 'UGX'), ('RWF', 'RWF'), ('BIF', 'BIF')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
