# Generated by Django 5.0.1 on 2024-06-19 20:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_delete_orderitem_order_currency_order_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userid', models.CharField(blank=True, max_length=200, null=True)),
                ('products', models.JSONField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=1000000000, null=True)),
                ('total_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=1000000000, null=True)),
                ('total_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=1000000000, null=True)),
                ('createdat', models.CharField(blank=True, max_length=200, null=True)),
                ('updatedat', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.JSONField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('ipaddress', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
