# Generated by Django 5.0.1 on 2024-06-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='qrcode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
