# Generated by Django 5.0.1 on 2024-06-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_transaction_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='updatedat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
