# Generated by Django 5.0.1 on 2024-06-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_message_updatedat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoggedIn',
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1, null=True),
        ),
    ]
