# Generated by Django 5.0.1 on 2024-06-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_profession_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='updatedAt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='jobid',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='tradepersonid',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
